# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import json


class Ui_Jax(object):
    def setupUi(self, Jax):
        Jax.setObjectName("Jax")
        Jax.resize(342, 357)
        self.Login = QtWidgets.QWidget(parent=Jax)
        self.Login.setObjectName("Login")
        self.UserName = QtWidgets.QLineEdit(parent=self.Login)
        self.UserName.setGeometry(QtCore.QRect(10, 100, 321, 31))
        self.UserName.setObjectName("UserName")
        self.Password = QtWidgets.QLineEdit(parent=self.Login)
        self.Password.setGeometry(QtCore.QRect(10, 180, 321, 31))
        self.Password.setObjectName("Password")
        self.pushButton = QtWidgets.QPushButton(parent=self.Login)
        self.pushButton.setGeometry(QtCore.QRect(90, 270, 151, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.Login_B)
        self.label = QtWidgets.QLabel(parent=self.Login)
        self.label.setGeometry(QtCore.QRect(60, 20, 221, 31))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        Jax.setCentralWidget(self.Login)
        self.label_2 = QtWidgets.QLabel(parent=self.Login)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 1, 1))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:red")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.EROR2 = QtWidgets.QLabel(parent=self.Login)
        self.EROR2.setGeometry(QtCore.QRect(20, 180, 1, 1))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EROR2.setFont(font)
        self.EROR2.setStyleSheet("color:red")
        self.EROR2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.EROR2.setObjectName("EROR2")
        Jax.setCentralWidget(self.Login)

        self.retranslateUi(Jax)
        QtCore.QMetaObject.connectSlotsByName(Jax)

    def retranslateUi(self, Jax):
        _translate = QtCore.QCoreApplication.translate
        Jax.setWindowTitle(_translate("Jax", "MainWindow"))
        self.pushButton.setText(_translate("Jax", "LOGIN"))
        self.label.setText(_translate("Jax", "WELLCOME"))

    def Login_B(self):
        User = self.UserName.text()
        Pass = self.Password.text()
        with open(r"Login & Sign-Up\Save.json", mode="r") as file:
            load = dict(json.load(file))
        if User == load["UserN"] and Pass == load["Password"]:
            print("WELLCOME BACK!")
            exit()
        else:
            self.UserName.setText("")
            self.Password.setText("")
            self.label_2.setText(("Password Or UserName Is Wrong!"))
            self.EROR2.setText(("Password Or UserName Is Wrong!"))
            self.label_2.setGeometry(QtCore.QRect(20, 100, 301, 31))
            self.EROR2.setGeometry(QtCore.QRect(20, 180, 301, 31))
            self.pushButton.clicked.connect(self.quit)
            self.pushButton.setText("Come Back Again!")

    def quit(self):
        exit()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Jax = QtWidgets.QMainWindow()
    ui = Ui_Jax()
    ui.setupUi(Jax)
    Jax.show()
    sys.exit(app.exec())
